// packages/vue-meeting-selector/src/components/meetingSelector/DayDisplay.vue
<template>
  <div class="day">
    <div class="day__title">
      {{ title }}
    </div>
    <div class="day__subtitle">
      {{ subtitle }}
    </div>
  </div>
</template>

<script
  setup
  lang="ts"
  generic="
    DateFieldKey extends string,
    MeetingSlotsKey extends string,
    MSlot extends MeetingSlot<DateFieldKey>,
    MDay extends MeetingsByDay<DateFieldKey, MeetingSlotsKey, MSlot>
  "
>
import { computed } from 'vue';
import type { MeetingSlot, MeetingsByDay } from 'common-meeting-selector';

const props = defineProps<{
  meetingsByDay: MDay;
  dateFieldKey: DateFieldKey;
  meetingSlotsKey: MeetingSlotsKey;
  daysLabel: string[];
  monthsLabel: string[];
}>();

const title = computed(() => {
  const date = new Date(props.meetingsByDay[props.dateFieldKey]);
  return props.daysLabel[date.getDay()];
});

const subtitle = computed(() => {
  const date = new Date(props.meetingsByDay[props.dateFieldKey]);
  return `${date.getDate()} ${props.monthsLabel[date.getMonth()]}`;
});
</script>

// packages/react-meeting-selector/src/components/meetingSelector/DayDisplay.tsx
import { type HTMLAttributes, memo, useMemo } from 'react';
import type { MeetingSlot, MeetingsByDay } from 'common-meeting-selector';

type DayDisplayProps<
  DateFieldKey extends string,
  MeetingSlotsKey extends string,
  MSlot extends MeetingSlot<DateFieldKey>,
  MDay extends MeetingsByDay<DateFieldKey, MeetingSlotsKey, MSlot>,
> = {
  meetingsByDay: MDay;
  dateFieldKey: DateFieldKey;
  meetingSlotsKey: MeetingSlotsKey;
  daysLabel: string[];
  monthsLabel: string[];
} & HTMLAttributes<HTMLElement>;

const DayDisplayComponent = <
  DateFieldKey extends string,
  MeetingSlotsKey extends string,
  MSlot extends MeetingSlot<DateFieldKey>,
  MDay extends MeetingsByDay<DateFieldKey, MeetingSlotsKey, MSlot>,
>({
  meetingsByDay,
  dateFieldKey,
  daysLabel,
  monthsLabel,
  className,
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  meetingSlotsKey,
  ...props
}: DayDisplayProps<DateFieldKey, MeetingSlotsKey, MSlot, MDay>) => {
  const date = useMemo(() => new Date(meetingsByDay[dateFieldKey]), [meetingsByDay, dateFieldKey]);

  const title = useMemo(() => {
    return daysLabel[date.getDay()];
  }, [date, daysLabel]);

  const subtitle = useMemo(() => {
    return `${date.getDate()} ${monthsLabel[date.getMonth()]}`;
  }, [date, monthsLabel]);

  return (
    <div className={`day ${className ?? ''}`} {...props}>
      <div className="day__title">{title}</div>
      <div className="day__subtitle">{subtitle}</div>
    </div>
  );
};

export const DayDisplay = memo(DayDisplayComponent) as typeof DayDisplayComponent;
