// devs/react-meeting-selector-dev/src/App.tsx
import { SimpleAsyncExample } from './components/SimpleAsyncExample';
import { SimpleExample } from './components/SimpleExample';
import { MultiExample } from './components/MultiExample';
import { MultipleRendersElementsExample } from './components/MultipleRendersElementsExample';

const App = () => (
  <>
    <h1>Simple example</h1>
    <SimpleExample />
    <h1>Simple async example</h1>
    <SimpleAsyncExample />
    <h1>Multi example</h1>
    <MultiExample />
    <h1>Multiple renders elements example</h1>
    <MultipleRendersElementsExample />
  </>
);

export default App;

// devs/vue-meeting-selector-dev/src/App.vue
<template>
  <div id="meeting-selector-dev">
    <h1>Simple example</h1>
    <SimpleExample />
    <h1>Simple async example</h1>
    <SimpleAsyncExample />
    <h1>Multi example</h1>
    <MultiExample />
    <h1>Slots example</h1>
    <SlotsExample />
  </div>
</template>

<script setup lang="ts">
import SimpleExample from './components/SimpleExample.vue';
import SimpleAsyncExample from './components/SimpleAsyncExample.vue';
import SlotsExample from './components/SlotsExample.vue';
import MultiExample from './components/MultiExample.vue';
</script>
